# Generated by Django 4.1.4 on 2022-12-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
    ]
